---
displayMode: compact
---

gantt
	title Assignment 2 FCFS (With I/O)
    dateFormat ss
    axisFormat %S

    section Running
    P1: 00, 1s
	P1: 02, 1s
	P2: 1s
	P1: 1s
	P2: 1s
	P1: 1s
	P2: 1s
	P1: 1s
	P3: 1s
	P2: 1s
	P1: 1s
	P3: 1s
	P4: 1s
	P2: 1s
	P1: 1s
	P5: 1s
	P3: 1s
	P4: 1s
	P2: 1s
	P1: 1s
	P5: 1s
	P3: 1s
	P4: 1s
	P2: 1s # Process 2 terminates
	P1: 1s
	P5: 1s
	P3: 1s
	P4: 1s
	P1: 1s
	P5: 1s
	P3: 1s
	P4: 1s
	P1: 1s
	P5: 1s
	P3: 1s
	P4: 1s
	P1: 1s
	P5: 1s
	P3: 1s
	P4: 1s
	P1: 1s
	P5: 1s
	P3: 1s
	P4: 1s
	P1: 1s
	P5: 1s
	P3: 1s
	P4: 1s
	P1: 1s
	P5: 1s
	P3: 1s
	P4: 1s
	P1: 1s
	P3: 1s
	P1: 1s
	P1: 57, 1s
