---
displayMode: compact
---

gantt
	title Assignment 2 Multi-level Feedback Queue (Without I/O)
    dateFormat ss
    axisFormat %S

    section High 
	P1: 00, 1s
	P2: 03, 1s
	P3: 10, 1s
	P4: 11, 1s
	P5: 14, 1s

    section Medium
	P1: 01, 2s
	P2: 04, 2s
	P3: 12, 2s
	P4: 15, 2s
	P5: 17, 2s

    section Low
	P1: 06, 4s
	P2: 19, 4s
	P1: 4s
	P3: 4s
	P4: 4s
	P5: 4s
	P1: 4s
	P3: 4s
	P4: 3s
	P5: 2s
	P1: 3s
	P3: 1s
