---
displayMode: compact
---

gantt
	title Assignment 2 Round Robin (Without I/O)
    dateFormat ss
    axisFormat %S

    section Running
    P1: 00, 3s
	P1: 3s
	P2: 3s
	P1: 3s
	P3: 3s
	P2: 3s
	P4: 3s
	P1: 3s
	P5: 3s
	P3: 3s
	P2: 1s
	P4: 3s
	P1: 3s
	P5: 3s
	P3: 3s
	P4: 3s
	P1: 3s
	P5: 3s
	P3: 3s
	P4: 1s
